# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts

on:
  push:
    tags:
      - v\d+\.\d+\.\d+

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          git clone https://github.com/searchscale/search-insights-collector
          cd search-insights-collector
          ls
          mvn clean compile assembly:single
          cp search-insights-collector.sh host-metrics.json ../downloads/.
          cp target/search-insights-collector*jar ../downloads/.
    
      - name: Step 3 - Upload Assets
        id: upload-assets
        uses: softprops/action-gh-release@v1
        with:
          files: downloads/*

